region: us-east-1

function_name: apilambdatest
handler: service.handler
description: Test for cross-region api gateway and lambda deployment.
runtime: python3.7
role: lambda_runner

build:
  source_directories: lib # a comma delimited list of directories in your project root that contains source to package.

# S3 upload requires appropriate role with s3:PutObject permission
# (ex. basic_s3_upload), a destination bucket, and the key prefix

# bucket_name: 'sv-cloud'
# s3_key_prefix: 'lambda_deployments/<function_name>'

# dist_directory: dist
# timeout: 15
# memory_size: 512
# concurrency: 1

# If `tags` is uncommented then tags will be set at creation or update
# time.  During an update all other tags will be removed except the tags
# listed here.
#tags:
#    tag_1: foo
#    tag_2: bar

# Build options

